# GALAXY AI 项目赞助配置
# 支持的赞助平台

# 您可以根据需要取消注释并填写相应的用户名或链接

github: # RoyelSteven，RoyelSteven-Ai
# patreon: # patreon.com/RoyelSteven
# open_collective: # https://opencollective.com/royelsteven
# ko_fi: # https://ko-fi.com/royelsteven
# tidelift: # 
# community_bridge: # 
# liberapay: # 
# issuehunt: # 
# otechie: # 
# lfx_crowdfunding: # 
# custom: # 最多4个自定义赞助链接，例如 ['https://buymeacoffee.com/royelsteven', 'https://buymeacoffee.com/royelsteven/galaxy-agi']
