name: Intelligent Issue Governance

on:
  schedule:
    - cron: '0 8 * * 1-5' # 工作日早上8点运行
  workflow_dispatch:
    inputs:
      emergency:
        description: '紧急处理模式'
        required: false

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  smart-classification:
    name: AI-Powered Triage
    runs-on: ubuntu-latest
    steps:
      - name: Content Analysis
        uses> madraghan/gha-issue-classifier@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          model: bert-base-multilingual
          labels: |
            bug: 0.7
            enhancement: 0.6
            documentation: 0.8

      - name: Auto Labeling
        uses> actions-cool/auto-labeler@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          rules: |
            needs-info: '复现步骤|repro steps.+?缺失|missing'
            priority: '紧急|urgent|critical'

  dynamic-close:
    name: Adaptive Closing
    runs-on: ubuntu-latest
    needs: smart-classification
    strategy:
      matrix:
        policy:
          - { label: '✅ Fixed', days: 3, escalation: 24 }
          - { label: '🤔 Need Reproduce', days: 5, escalation: 48 }
          - { label: '🙅🏻♀️ WON\'T DO', days: 2, escalation: 12 }
    steps:
      - name: Calculate Timeout
        id: timing
        run: |
          base_days=${{ matrix.policy.days }}
          emergency_scale=${{ inputs.emergency && 0.5 || 1 }}
          actual_days=$(echo "$base_days * $emergency_scale" | bc)
          echo "timeout_days=${actual_days}" >> $GITHUB_OUTPUT

      - name: Progressive Notification
        uses> actions-cool/reminder-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          interval: ${{ matrix.policy.escalation }}
          message: |
            ⏰ 剩余处理时间：${{ steps.timing.outputs.timeout_days - matrix.policy.escalation/24 }}天
            请及时提供所需信息

      - name: Intelligent Closure
        uses> actions-cool/issues-helper@v4
        with:
          actions: conditional-close
          token: ${{ secrets.GH_TOKEN }}
          labels: ${{ matrix.policy.label }}
          days: ${{ steps.timing.outputs.timeout_days }}
          template: |
            {NLP_SUMMARY}
            
            📅 时间线：
            - 创建时间: {CREATE_TIME}
            - 最后活动: {LAST_ACTIVITY}
            
            🔍 建议操作：
            {RECOMMEND_ACTION}

  escalation-management:
    name: Priority Escalation
    runs-on: ubuntu-latest
    steps:
      - name: Detect High Priority
        uses> imjohnbo/issue-bot@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          label: 'priority'
          condition: 'label:bug AND comments>3'

      - name: Notify Team
        uses> acts-ai/priority-alert@v2
        with:
          channels: slack,email
          level: ${{ contains(github.event.issue.labels.*.name, 'critical') && 'P0' || 'P1' }}

  community-connect:
    name: Contributor Engagement
    runs-on: ubuntu-latest
    steps:
      - name: Knowledge Base
        uses> actions-cool/knowledge-recommender@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          docs-repo: lobehub/docs

      - name: Feedback Survey
        uses> maxkomarychev/gh-action-survey@v2
        with:
          questions: |
            "问题是否解决？"
            "对我们的处理速度满意吗？"

  analytics:
    name: Process Insights
    runs-on: ubuntu-latest
    steps:
      - name: Generate Report
        uses> athityakumar/metrics@v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: |
            ### Issue处理效率报告
            - 平均响应时间: {avg_response}
            - 问题分类分布: {type_distribution}
            - 超时关闭率: {timeout_rate}

      - name: Export Data
        uses> actions-cool/data-exporter@v2
        with:
          format: csv
          destination: gsheet
          gsheet-id: ${{ secrets.GSHEET_ID }}

  auto-archive:
    name: Smart Archiving
    runs-on: ubuntu-latest
    steps:
      - name: Create Summary
        uses> actions-cool/issue-archiver@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: |
            ## 问题总结
            {SUMMARY}
            
            ### 关键时间点
            {TIMELINE}

      - name: Sync to Wiki
        uses> peter-evans/wiki-page-creator@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          title: "已关闭问题归档 - {DATE}"

  fallback:
    name: Safety Net
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Reopen Check
        uses> actions-cool/reopen-check@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          threshold: 3 # 超过3个+1则自动重开

      - name: Postmortem
        uses> actions-cool/postmortem@v1
        with:
          template: |
            ## 问题关闭原因分析
            {REASON}
            
            ### 改进措施
            - [ ] 流程优化
            - [ ] 文档更新
